services:
  app:
    image: ghcr.io/mptwaktusolat/api-waktusolat-x:main
    restart: unless-stopped
    environment:
      # Enable opcache in production
      - PHP_OPCACHE_ENABLE=1
      # Reverse proxy settings
      - ENABLE_TRUSTED_PROXY_CONFIG=true
      - TRUSTED_PROXIES=*
      # Enable Laravel automation: https://serversideup.net/open-source/docker-php/docs/framework-guides/laravel/automations
      - AUTORUN_ENABLED=true
    env_file:
      - stack.env
    depends_on:
      - db
    networks:
      - default
      - reverse_proxy

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: waktusolat
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

volumes:
  db_data:

networks:
  default:
  reverse_proxy:
    name: proxy
    external: true